name: npm-publish
on:
  push:
    branches:
      - main

jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Publish to NPM
        id: publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
          strategy: upgrade

      - name: Create Git Tag
        if: steps.publish.outputs.type != 'none'
        run: |
          git tag v${{ steps.publish.outputs.version }}
          git push origin --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
