name: Pull Request

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install, build, and test
        run: |
          npm ci
          npm run build
          npm test

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Rebuild changes
          branch: ${{ github.head_ref }}
          commit_user_name: tiliavir
          commit_user_email: tiliavir@users.noreply.github.com

      - name: Dependabot Auto Merge
        if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}
        run: |
          echo "$GITHUB_CONTEXT"
          gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GH_ACTION_MERGER_TOKEN }}
