name: Update Dependencies
on:
  schedule:
    - cron:  '30 17 * * 2'
  workflow_dispatch:
jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Update dependencies
        id: vars
        run: |
          npm install -g npm-check-updates
          ncu -u
          npm install
          npm run build
          npm run test
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            commit-message: update dependencies
            committer: GitHub <noreply@github.com>
            author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
            signoff: false
            base: master
            branch: dependencies
            branch-suffix: timestamp
            delete-branch: true
            title: 'Automated Dependency Updates'
            body: This is an auto-generated PR with dependency updates.
            labels: dependencies
            assignees: tiliavir
            reviewers: tiliavir
            team-reviewers: |
                owners
                maintainers
